In [ ]:
#DAY 7
import numpy as np

In [ ]:
x=np.array([10,20,30,40,50,60,70,80,90])
print(x)

[10 20 30 40 50 60 70 80 90]


In [ ]:
x=np.array([[10,20,30],[40,50,60]])
print(x)

[[10 20 30]
 [40 50 60]]


In [ ]:
x=np.zeros(20)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
x=np.zeros((2,3),dtype=int)
print(x)
print(x.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [ ]:
x=np.ones(20)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
x=np.full(10,7)
print(x)

[7 7 7 7 7 7 7 7 7 7]


In [ ]:
x=np.arange(1,20)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
x=np.empty((7,8))
print(x)
#It creates a 2D array with 7 rows and 8 columns, but it does NOT initialize the values.

[[ 4.16617275e-315  0.00000000e+000  1.51365230e+241  4.80880511e+199
   1.71877509e+161  5.28595560e-085  1.93437538e+142  4.53801769e+279]
 [ 4.28051344e+160  1.05894212e-153  2.30270783e+242  4.55072052e+198
   1.51377104e+241  4.93613705e+180  1.30139612e-288  4.42993235e+015]
 [ 1.90079827e+132  8.74971243e-153  1.90081733e+132  3.68065909e+180
   3.83467371e+141 -4.60082593e-292  7.30928081e-313  1.55532739e+241]
 [ 3.52780343e+160  1.27849494e-152  7.48551511e+247  4.53801769e+279
   7.72493424e+228  1.90081733e+132  3.68065906e+180  7.69825529e+218]
 [ 3.56414066e+262  2.87414383e-312  2.94213868e-307  5.02727739e+175
   2.18226624e+243  8.78536345e+223  1.06400250e+248  1.33360359e+241]
 [ 9.47683320e-311 -6.04608851e-138  6.98846729e+228  6.56740901e-306
   1.33360367e+241  9.53073190e-310 -4.03154055e+103  8.79467787e-313]
 [ 1.50637500e-304  1.33360309e+241  2.14279135e-310  4.25633211e+180
   3.99194028e+252 -5.64351359e+204  5.12345937e-312  6.19283252e-310]]


In [ ]:
x=np.array([[10,20,3],[40,50,60]])
print(x)
print(x.shape)
print(x.dtype)
print(x.ndim)
print(x.size)

[[10 20  3]
 [40 50 60]]
(2, 3)
int64
2
6


In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x,y)
print(x+y)

[1 2 3] [4 5 6]
[5 7 9]


In [ ]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[1,2,3],[4,5,6]])
print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]


In [ ]:
x=np.arange(1,11)
y=np.arange(11,21)
print(x)
print(y)
ans=np.sum(x)
ans1=np.sum(y)
print(ans)
print(ans1)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
55
155


In [ ]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
ans=np.sum(x)
print(ans)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


In [ ]:
ans1=np.sum(x,axis=0)
print(ans1)

[12 15 18]


In [ ]:
ans2=np.sum(x,axis=1)
print(ans2)

[ 6 15 24]


In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
ans2=np.mean(x)
ans3=np.median(x)
ans4=np.min(x)
ans5=np.max(x)
print(ans2)
print(ans3)
print(ans4)
print(ans5)

5.5
5.5
1
10


In [ ]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
ans6=np.sum(x,axis=1)
print(x)
print(ans6)
ans7=np.min(x,axis=0)
print(ans7)
ans8=np.max(x,axis=1)
print(ans8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]
[1 2 3]
[3 6 9]


In [ ]:
z=np.array([[[1,2,3],[4,5,6]],
           [[7,8,9],[10,11,12]]])
print(z)
print(z.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
#Operations on 3D Array
print(np.sum(z))
print(np.sum(z,axis=0))
print(np.sum(z,axis=1))
print(np.sum(z,axis=2))
print(np.min(z))
print(np.max(z))
print(np.mean(z))
print(np.median(z))

78
[[ 8 10 12]
 [14 16 18]]
[[ 5  7  9]
 [17 19 21]]
[[ 6 15]
 [24 33]]
1
12
6.5
6.5


In [ ]:
y = np.ones((2,2,3))
print((y))

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#DAY 8 WEDNESDAY
#basic of slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[:-1])
print(arr[-1])
print(arr[:3])
print(arr[1:10])
print(arr[:-1])


[1 2 3 4 5 6 7 8 9]
10
[1 2 3]
[ 2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#reshaping converting matrix from one dimension to other
a=np.array([1,2,3,4,5,6])
print(a.shape)

(6,)


In [ ]:
a1=a.reshape(2,3)
print(a1)

[[1 2 3]
 [4 5 6]]


In [ ]:
a2=a.reshape(3,2)
print(a2)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
x3=np.arange(12)
b1=x3.reshape(3,-1) #fixing number of rows, columns will be automatically selected
print(b1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
x4=np.arange(24)
b1=x4.reshape(-1,4) #fixing number of columns, rows will be automatically selected
print(x4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
#any dimension to 1d array (2D TO 1D)
#flatten function
a=np.arange(12).reshape(3,4)  #2D ARRAY
print(a)
print(a.shape)

a1=a.flatten()
print(a1)
print(a1.shape)


x1=np.arange(24).reshape(4,3,2)  #multidiemnsional array
print(x1)
print(x1.shape)

b2=x1.flatten()
print(b2)
print(b2.shape)


#F COLUMN WISE
#C ROW WISE
#K MEMORY WISE

b3=x3.flatten(order="F")
print(b3)
print(b3.shape)

b4=x3.flatten(order="C")
print(b4)
print(b4.shape)

#memory wise
b4=x3.flatten(order="K")
print(b4)
print(b4.shape)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
(4, 3, 2)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [ ]:
#TASK
#1 Array Creation
#Create a NumPy array of numbers from 1 to 20. Then print its size.

import numpy as np
arr=np.arange(1,21)
print(arr)
print(arr.size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
20


In [ ]:
#2. Zeros & Ones
#Create:
#a 3×4 array filled with zeros
#a 2×5 array filled with ones

import numpy as np
# 3x4 array of zeros
zeros_array = np.zeros((3, 4))
print(zeros_array)

# 2x5 array of ones
ones_array = np.ones((2, 5))
print(ones_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#3. Full Function
#Create a 4×4 array where every value is 7 using NumPy.

import numpy as np
arr = np.full((4, 4), 7)
print(arr)


[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
#4. Reshape
#Create an array from 1 to 12 and reshape it into:
#3×4
#2×6

import numpy as np
arr = np.arange(1, 13)
print(arr)

# Reshape to 3x4
arr1 = arr.reshape(3, 4)
print(arr1)

# Reshape to 2x6
arr2 = arr.reshape(2, 6)
print(arr2)



Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
#5. Flatten
#Take a 3×3 matrix and convert it into a 1D array using flatten.

import numpy as np
x= np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(x)
y = x.flatten()
print(y)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#6. Arrange (arange)
#Create an array starting from 10 to 50 with a step of 5.

import numpy as np
arr = np.arange(10, 51, 5)
print(arr)


[10 15 20 25 30 35 40 45 50]


In [ ]:
#7. Sum of Elements
#Given array:
#[10, 20, 30, 40, 50]
#Find:
#total sum
#sum of first 3 elements only

import numpy as np
arr = np.array([10, 20, 30, 40, 50])

print(arr)

total_sum = np.sum(arr)
print(total_sum)

first_three_sum = np.sum(arr[:3])
print(first_three_sum)


[10 20 30 40 50]
150
60


In [ ]:
#8. Matrix Addition
#Add the following two arrays:

#A = [[1,2,3],
#     [4,5,6]]


#B = [[6,5,4],
#    [3,2,1]]

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[6, 5, 4],
              [3, 2, 1]])

print(A)
print(B)

# Matrix Addition
C = A + B
print(C)


[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]
[[7 7 7]
 [7 7 7]]


In [ ]:
#9. Matrix Subtraction
#Subtract array B from array A (from Q8).

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[6, 5, 4],
              [3, 2, 1]])

print(A)
print(B)
C = A - B
print(C)


[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]
[[-5 -3 -1]
 [ 1  3  5]]


In [ ]:
#10. Element-wise Multiplication
#Multiply arrays A and B element by element.

import numpy as np
A = np.array([[1, 2],
              [4, 5]])

B = np.array([[6, 5],
              [3, 2]])

print(A)
print(B)
C = A * B
print(C)
D=np.matmul(A,B)
print(D)


[[1 2]
 [4 5]]
[[6 5]
 [3 2]]
[[ 6 10]
 [12 10]]
[[12  9]
 [39 30]]


In [ ]:
#11. Mean
#Find the mean of:
#[12, 15, 20, 25, 30]

import numpy as np
arr = np.array([12, 15, 20, 25, 30])

print(arr)
mean_value = np.mean(arr)

print(mean_value)



[12 15 20 25 30]
20.4


In [ ]:
#12. Median
#Find the median of:
#[5, 2, 9, 1, 7, 6]
import numpy as np
arr = np.array([5, 2, 9, 1, 7, 6])

print(arr)
median_value = np.median(arr)

print(median_value)



[5 2 9 1 7 6]
5.5


In [ ]:
#13. Standard Deviation
#Find the standard deviation of:
#[4, 8, 6, 5, 3, 7]

import numpy as np
arr = np.array([4, 8, 6, 5, 3, 7])

print(arr)
std_dev = np.std(arr)

print(std_dev)


[4 8 6 5 3 7]
1.707825127659933


In [ ]:
#14. Row-wise Sum
#Given matrix:

#[[1,2,3],
# [4,5,6],
# [7,8,9]]

import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix)
row_sum = np.sum(matrix, axis=1)
print(row_sum)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]


In [ ]:
#15. Column-wise Sum
#Using the same matrix from Q14, find sum of each column.

import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix)
col_sum = np.sum(matrix, axis=0)
print(col_sum)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]


In [ ]:
#16. Reshape + Mean
#Create numbers from 1 to 16, reshape into 4×4, then find the mean of each row.

import numpy as np
arr = np.arange(1, 17)
print(arr)

matrix = arr.reshape(4, 4)
print(matrix)
row_mean = np.mean(matrix, axis=1)
print(row_mean)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 2.5  6.5 10.5 14.5]


In [ ]:
#17. Flatten + Size
#Create a 5×5 ones matrix. Flatten it and find its size.

import numpy as np
matrix = np.ones((5, 5))
print(matrix)

flat_array = matrix.flatten()
print(flat_array)
print(flat_array.size)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]
25


In [ ]:
#18. Arithmetic Combination
#Given:
#A = [1,2,3,4]
#B = [5,6,7,8]

#Compute:
#(A + B) * 2

import numpy as np
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

print(A)
print(B)

result = (A + B) * 2
print(result)


[1 2 3 4]
[5 6 7 8]
[12 16 20 24]


In [ ]:
#19. Mixed Operations
#Create array from 1–9, reshape to 3×3. Multiply entire matrix by 5 and then find total sum.

import numpy as np
arr = np.arange(1, 10)
print(arr)

matrix = arr.reshape(3, 3)
print(matrix)

multiplied = matrix * 5
print(multiplied)

total_sum = np.sum(multiplied)
print(total_sum)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
225


In [ ]:
#20. Statistics Combo
#Given:
#[15, 18, 21, 24, 27, 30]
import numpy as np
arr = np.array([15, 18, 21, 24, 27, 30])

print(np.mean(arr))
print("Median:", np.median(arr))

print("Standard Deviation:", np.std(arr))


22.5
Median: 22.5
Standard Deviation: 5.123475382979799


In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
a=x[-2:2]
print(a)

[]


In [ ]:
#DAY9

#HARD QUESTIONS
#1. Advanced Reshape + Sum
#Create an array from 1 to 48.
#Reshape it into 4 × 4 × 3.
#Find:
#sum along axis 0
#sum along axis 1
#sum along axis 2

import numpy as np

arr = np.arange(1, 49)      # 1 to 48
arr = arr.reshape(4, 4, 3)  # 4 × 4 × 3

print(arr)


sum1= np.sum(arr, axis=0)
print(sum1)

sum2= np.sum(arr, axis=1)
print(sum2)

sum3= np.sum(arr, axis=2)
print(sum3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]
[[ 76  80  84]
 [ 88  92  96]
 [100 104 108]
 [112 116 120]]
[[ 22  26  30]
 [ 70  74  78]
 [118 122 126]
 [166 170 174]]
[[  6  15  24  33]
 [ 42  51  60  69]
 [ 78  87  96 105]
 [114 123 132 141]]


In [ ]:
#2. Conditional Replacement
#Create array from 1 to 20.
#Replace all numbers:
#divisible by 3 → -1
#divisible by 5 → 100
#(Do it using NumPy, not loops.)

import numpy as np
arr=np.arange(1,21)
print(arr)
a=np.where(arr%3==0,-1,arr)
a=np.where(arr%5==0,100,arr)
print(a)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   2   3   4 100   6   7   8   9 100  11  12  13  14 100  16  17  18
  19 100]


In [ ]:
#3. Broadcasting Math
#Given:
#A = np.array([[1,2,3],
#              [4,5,6],
#              [7,8,9]])
#B = np.array([10,20,30])
#Add B to every row of A using broadcasting.

import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([10,20,30])
result = A + B
print(result)


[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
#4. Flatten vs Ravel Logic
#Create a 3×3 matrix.
#Use ravel() to flatten and modify the first element.
#Then check whether original array changes.
#Explain why.

import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(A)
flat=A.ravel()
flat[0] = 999
print(flat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[999   2   3   4   5   6   7   8   9]


In [ ]:
#5. Indexing Challenge
#Create array 1–25 and reshape to 5×5.
#Extract:
#middle row
#last column
#corner elements only

import numpy as np

arr = np.arange(1, 26).reshape(5, 5)
print(arr)

middle_row = arr[2]
print(middle_row)

last_column = arr[: ,-1]
print(last_column)

corner = arr[0,0], arr[0,-1], arr[-1,0], arr[-1,-1]
print(corner)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[11 12 13 14 15]
[ 5 10 15 20 25]
(np.int64(1), np.int64(5), np.int64(21), np.int64(25))


In [ ]:
#6. Statistical Axis Problem

#Given:

#arr = np.array([[10,20,30],
#                [40,50,60],
#                [70,80,90]])
#Find:
#mean of each column
#standard deviation of each row

import numpy as np

arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

print(arr)
col_mean = np.mean(arr, axis=0)
print(col_mean)

row_std = np.std(arr, axis=1)
print(row_std)



[[10 20 30]
 [40 50 60]
 [70 80 90]]
[40. 50. 60.]
[8.16496581 8.16496581 8.16496581]


In [ ]:
#7. Matrix Arithmetic Combo
#Create two random 3×3 arrays.
#Compute:
#(A + B) * 2 - A

a= np.random.randint(1,10,(3,3))
b= np.random.randint(1,10,(3,3))
print(a)
print(b)
result = (A + B) * 2 - A
print(result)

[[4 9 3]
 [1 5 2]
 [9 2 1]]
[[1 7 9]
 [1 6 4]
 [2 4 5]]
[[1019   42   63]
 [  24   45   66]
 [  27   48   69]]


In [ ]:
#8. Pattern Matrix

#Create this matrix using NumPy only:

#[[1,0,1,0],
# [0,1,0,1],
# [1,0,1,0],
# [0,1,0,1]]

#(No manual typing.)

a=np.arange(1,17).reshape(4,4)
result =a%2
print(result)


[[1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]]


In [ ]:
#9. 3D Array Stats

#Create array from 1–27 and reshape to 3×3×3.
#Find:

#overall mean
#mean along axis 0
#median of entire array

import numpy as np

arr = np.arange(1, 28).reshape(3, 3, 3)
print(arr)

overall_mean = np.mean(arr)
print(overall_mean)

mean1= np.mean(arr,axis=0)
print(mean1)

median= np.median(arr)
print(median)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
14.0
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
14.0


In [ ]:
#10. Multi-step Transformation

#Create array from 1–16.
#Steps:

#Reshape to 4×4

#Multiply each column by [1,2,3,4]

#Flatten result

#Find standard deviation

a=np.arange(1,17).reshape(4,4)
print(a)
mul=np.array([1,2,3,4])
result=a*mul
print(result)

flat= result.flatten()
print(flat)

standarddev= np.std(flat)
print(standarddev)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  4  9 16]
 [ 5 12 21 32]
 [ 9 20 33 48]
 [13 28 45 64]]
[ 1  4  9 16  5 12 21 32  9 20 33 48 13 28 45 64]
17.38533865071371
